import type { BookInfo } from "@/types";

/**
 * All 66 books of the Bible with their abbreviations (for bible-api.com)
 * and chapter counts. Used for random chapter selection.
 */
export const BIBLE_BOOKS: BookInfo[] = [
  // Old Testament
  { abbr: "GEN", name: "Genesis", chapters: 50, index: 0 },
  { abbr: "EXO", name: "Exodus", chapters: 40, index: 1 },
  { abbr: "LEV", name: "Leviticus", chapters: 27, index: 2 },
  { abbr: "NUM", name: "Numbers", chapters: 36, index: 3 },
  { abbr: "DEU", name: "Deuteronomy", chapters: 34, index: 4 },
  { abbr: "JOS", name: "Joshua", chapters: 24, index: 5 },
  { abbr: "JDG", name: "Judges", chapters: 21, index: 6 },
  { abbr: "RUT", name: "Ruth", chapters: 4, index: 7 },
  { abbr: "1SA", name: "1 Samuel", chapters: 31, index: 8 },
  { abbr: "2SA", name: "2 Samuel", chapters: 24, index: 9 },
  { abbr: "1KI", name: "1 Kings", chapters: 22, index: 10 },
  { abbr: "2KI", name: "2 Kings", chapters: 25, index: 11 },
  { abbr: "1CH", name: "1 Chronicles", chapters: 29, index: 12 },
  { abbr: "2CH", name: "2 Chronicles", chapters: 36, index: 13 },
  { abbr: "EZR", name: "Ezra", chapters: 10, index: 14 },
  { abbr: "NEH", name: "Nehemiah", chapters: 13, index: 15 },
  { abbr: "EST", name: "Esther", chapters: 10, index: 16 },
  { abbr: "JOB", name: "Job", chapters: 42, index: 17 },
  { abbr: "PSA", name: "Psalms", chapters: 150, index: 18 },
  { abbr: "PRO", name: "Proverbs", chapters: 31, index: 19 },
  { abbr: "ECC", name: "Ecclesiastes", chapters: 12, index: 20 },
  { abbr: "SNG", name: "Song of Solomon", chapters: 8, index: 21 },
  { abbr: "ISA", name: "Isaiah", chapters: 66, index: 22 },
  { abbr: "JER", name: "Jeremiah", chapters: 52, index: 23 },
  { abbr: "LAM", name: "Lamentations", chapters: 5, index: 24 },
  { abbr: "EZK", name: "Ezekiel", chapters: 48, index: 25 },
  { abbr: "DAN", name: "Daniel", chapters: 12, index: 26 },
  { abbr: "HOS", name: "Hosea", chapters: 14, index: 27 },
  { abbr: "JOL", name: "Joel", chapters: 3, index: 28 },
  { abbr: "AMO", name: "Amos", chapters: 9, index: 29 },
  { abbr: "OBA", name: "Obadiah", chapters: 1, index: 30 },
  { abbr: "JON", name: "Jonah", chapters: 4, index: 31 },
  { abbr: "MIC", name: "Micah", chapters: 7, index: 32 },
  { abbr: "NAM", name: "Nahum", chapters: 3, index: 33 },
  { abbr: "HAB", name: "Habakkuk", chapters: 3, index: 34 },
  { abbr: "ZEP", name: "Zephaniah", chapters: 3, index: 35 },
  { abbr: "HAG", name: "Haggai", chapters: 2, index: 36 },
  { abbr: "ZEC", name: "Zechariah", chapters: 14, index: 37 },
  { abbr: "MAL", name: "Malachi", chapters: 4, index: 38 },
  // New Testament
  { abbr: "MAT", name: "Matthew", chapters: 28, index: 39 },
  { abbr: "MRK", name: "Mark", chapters: 16, index: 40 },
  { abbr: "LUK", name: "Luke", chapters: 24, index: 41 },
  { abbr: "JHN", name: "John", chapters: 21, index: 42 },
  { abbr: "ACT", name: "Acts", chapters: 28, index: 43 },
  { abbr: "ROM", name: "Romans", chapters: 16, index: 44 },
  { abbr: "1CO", name: "1 Corinthians", chapters: 16, index: 45 },
  { abbr: "2CO", name: "2 Corinthians", chapters: 13, index: 46 },
  { abbr: "GAL", name: "Galatians", chapters: 6, index: 47 },
  { abbr: "EPH", name: "Ephesians", chapters: 6, index: 48 },
  { abbr: "PHP", name: "Philippians", chapters: 4, index: 49 },
  { abbr: "COL", name: "Colossians", chapters: 4, index: 50 },
  { abbr: "1TH", name: "1 Thessalonians", chapters: 5, index: 51 },
  { abbr: "2TH", name: "2 Thessalonians", chapters: 3, index: 52 },
  { abbr: "1TI", name: "1 Timothy", chapters: 6, index: 53 },
  { abbr: "2TI", name: "2 Timothy", chapters: 4, index: 54 },
  { abbr: "TIT", name: "Titus", chapters: 3, index: 55 },
  { abbr: "PHM", name: "Philemon", chapters: 1, index: 56 },
  { abbr: "HEB", name: "Hebrews", chapters: 13, index: 57 },
  { abbr: "JAS", name: "James", chapters: 5, index: 58 },
  { abbr: "1PE", name: "1 Peter", chapters: 5, index: 59 },
  { abbr: "2PE", name: "2 Peter", chapters: 3, index: 60 },
  { abbr: "1JN", name: "1 John", chapters: 5, index: 61 },
  { abbr: "2JN", name: "2 John", chapters: 1, index: 62 },
  { abbr: "3JN", name: "3 John", chapters: 1, index: 63 },
  { abbr: "JUD", name: "Jude", chapters: 1, index: 64 },
  { abbr: "REV", name: "Revelation", chapters: 22, index: 65 },
];

/** Total chapters across the entire Bible */
export const TOTAL_CHAPTERS = BIBLE_BOOKS.reduce((s, b) => s + b.chapters, 0);
